# Generated by Django 3.0.2 on 2020-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('sort', models.SmallIntegerField()),
            ],
        ),
    ]
